name: Test

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 3 1 * *'  # <https://crontab.guru/#45_16_*_*_0> 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |
          ./run_tests.sh
